### PR TITLE
Socket.io namespaces support

### PR DESCRIPTION
**Pull request by sdvallejo**
Hello, 
I made a change to support namespaces. Could you please review it?

### CODE REVIEW

**Comment by Sammaye** [comment]
Yeah, might be good to also add a `setNamespace` function so you don't have to call it on every emit.

Also the `if` needs braces.

**Comment by Sammaye** [comment]
For coding standards I mean, this repo follows the Yii2 psr-2 standard

**Comment by sdvallejo** [comment]
Thanks for the suggestions! I made the changes on the code.

**Comment by Sammaye** [comment]
Thanks for the contrib

**Pull request merged**
